version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.14
  pre_build:
    commands:
      - echo "Environment Variables:"
      - printenv
      - apt update -y
      - apt install rpm -y
  build:
    commands:
      - cat go.mod
      - make release
artifacts:
  files:
    - '**/*'
  discard-paths: no
