version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  pre_build:
    commands:
      - echo "Environment Variables:"
      - printenv
      - apt-get update
      - apt-get install rpm -y
      #- apt-get update
  build:
    commands:
      - cat go.mod
      - make release
artifacts:
  files:
    - '**/*'
  discard-paths: no
